alignment fix
tmhub/easycatalogimg pull request #13
Opened 2018-04-12 18:16 UTC by mpalasis

Long category names break grid alignment.
Fix alignment issues by placing text below image.

2018-04-12 18:27 UTC, mpalasis commented
# Before

![sample-bad-alignment](https://user-images.githubusercontent.com/37408939/38696479-f409660e-3e97-11e8-9740-93be1202cbe6.JPG)

# After

![sample-alignment-fixed](https://user-images.githubusercontent.com/37408939/38696484-f8c98a34-3e97-11e8-917b-f54c5547b2bf.JPG)

(ignore the image dimensions and fonts, 'before' snapshot was old)

2018-04-13 06:49 UTC, vovayatsyuk commented
Thank you for your PR.

While the idea is great, we can't accept it, because there are multiple themes that already uses category title above the image as a part of homepage design (Our Argento themes).

We would accept this change if you'll add the possibility to render the category title above the image.

**Have a look how it's done in M2 module:**

https://github.com/swissup/easycatalogimg/blob/master/view/frontend/layout/easycatalogimg_departments_view.xml#L12

```xml
<argument name="parent_category_position" xsi:type="string">bottom</argument>
```

https://github.com/swissup/easycatalogimg/blob/master/view/frontend/templates/list.phtml#L29-L31:

```php
<?php if ($block->getParentCategoryPosition() === 'top') : ?>
    <div class="category-name parent-category parent-category-top"><a href="<?php echo $_category->getUrl() ?>" title="<?php echo $block->escapeHtml($_category->getName()) ?>"><?php echo $block->escapeHtml($_category->getName()) ?></a></div>
<?php endif ?>

...

<?php if ($block->getParentCategoryPosition() !== 'top') : ?>
    <div class="category-name parent-category"><a href="<?php echo $_category->getUrl() ?>" title="<?php echo $block->escapeHtml($_category->getName()) ?>"><?php echo $block->escapeHtml($_category->getName()) ?></a></div>
<?php endif ?>
```

https://github.com/swissup/easycatalogimg/blob/master/Block/SubcategoriesList.php#L320-L326:

```php
public function getParentCategoryPosition()
{
    if ($this->hasData('parent_category_position')) {
        return $this->getData('parent_category_position');
    }
    return 'top';
}
```

2018-04-13 19:38 UTC, mpalasis commented
added options

2018-04-13 20:18 UTC, vovayatsyuk requested changes
Thank you. Waiting for the next few fixes.

2018-04-13 20:36 UTC, mpalasis commented
done :)

2018-04-13 21:06 UTC, mpalasis commented
Take a look at
(WIP) https://github.com/mpalasis/easycatalogimg/tree/add-jcarousel
I think that's what you where intending to go with the widget part of this ;)

2018-04-14 06:50 UTC, vovayatsyuk approved these changes
Great, thank you!

2018-04-14 06:57 UTC, merged

2018-04-14 07:00 UTC, vovayatsyuk commented
As for the carousel, you can try https://github.com/tmhub/slick-carousel.

Docs: http://docs.swissuplabs.com/m1/extensions/slick-carousel/

2018-04-14 15:44 UTC, mpalasis commented
slick.js 's factory loader fails to resolve jQuery/$ properly and breaks my site, I just rolled my eyes and used jcarousel instead... maybe I'll look into it again later.